import Navbar from "../components/Navbar";
import Hero from "../components/Hero";
import Aboutus from "../components/Aboutus";
import Gallery from "../components/Gallery";
import Client from "../components/Client";
import CompanyProfile from "../components/CompanyProfile";
import Footer from "../components/Footer";
import Services from "../components/Services";
import ToTop from "../components/ToTop.js";
import Head from "next/head";
import { useRef, useState } from "react";
import Button from "../components/Button.js";
import ModalOne from "../components/ModalOne.js";
import ModalTwo from "../components/ModalTwo.js";

export default function index() {
	const home = useRef(null);
	const aboutus = useRef(null);
	const clients = useRef(null);
	const services = useRef(null);
	const gallery = useRef(null);
	const companyProfile = useRef(null);
	const allDirectTo = [
		home,
		aboutus,
		clients,
		services,
		gallery,
		companyProfile,
	];
	const [isOpen1, setIsOpen1] = useState(false);
	const [isOpen2, setIsOpen2] = useState(false);

	return (
		<>
			<Head>
				<title>PT. Kurnia Gemilang Bersama</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar directs={allDirectTo} />
			<Hero directTo={home} />
			<Aboutus directTo={aboutus}>
				<Button type="secondary" onClick={() => setIsOpen1(true)}>
					Read more
				</Button>
			</Aboutus>
			<Client directTo={clients}>
				<Button type="primary" onClick={() => setIsOpen2(true)}>
					Read more
				</Button>
			</Client>
			<Services directTo={services} />
			<Gallery directTo={gallery} />
			<CompanyProfile directTo={companyProfile} />
			<ModalOne
				isOpen1={isOpen1}
				setIsOpen1={setIsOpen1}
				title="Services"
				description="Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum enim inventore ab eos similique? Facilis commodi quasi distinctio eum voluptate."
			/>
			<ModalTwo
				isOpen2={isOpen2}
				setIsOpen2={setIsOpen2}
				title="Clients"
				description="Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum enim inventore ab eos similique? Facilis commodi quasi distinctio eum voluptate."
			/>
			<ToTop />
			<Footer />
		</>
	);
}
